"""The launchd jobs, generated from the task registry instead of committed.

Eight `.plist` files used to live in `launchd/`, and every one of them was the
same file with four things swapped: a label, a module name, a time, and a log
path. All four already sit in `scribejay/core/registry.py`, so the files were a
second copy of that table — one that a new task, a moved schedule or a renamed
log could put out of step without anything noticing.

Generating them buys the thing Phase 3 was for. `registry.enabled_tasks()`
returns only the tasks whose features the user actually wants, so a user with
no Strava never gets `local.scribejay.stravadownload` installed at all. Before,
the job was installed regardless and skipped politely every morning; now it is
simply absent.

**The interpreter is `sys.executable`.** Whatever python is running this command
is the one the jobs will exec — the tool's own venv after `uv tool install`,
`.venv/bin/python` in a source checkout. launchd expands neither `~` nor
`$PATH`, so an absolute path is the only thing that works, and asking the
running interpreter is the only way to get the right one.

**`local.scribejay.selfheal` is not generated and is not touched here.** It runs
under Apple-signed `/bin/bash` on purpose, so that it still starts when a brew
upgrade has left the python interpreter unexecutable — the exact failure it
exists to repair. Routing it through this module would hand it the interpreter
it is supposed to be independent of. It stays a committed file in `launchd/`,
installed by `launchd/install.sh`. `status` below reports it if it is loaded, so
a user is not left wondering where it went.
"""

import os
import plistlib
import subprocess
import sys
from pathlib import Path

from scribejay.core import config, registry

LAUNCH_AGENTS = Path.home() / "Library" / "LaunchAgents"

LABEL_PREFIX = "local.scribejay."

# Not generated by this module; see the module docstring. Named so `remove` can
# leave it alone and `status` can still mention it.
SELFHEAL_LABEL = LABEL_PREFIX + "selfheal"

_INSTALL_ROOT = Path(__file__).resolve().parent.parent.parent


def working_directory() -> Path:
    """The `cwd` each job runs in.

    A source checkout keeps its repo root, which is what the eight committed
    plists set and what a relative path setting on an existing install still
    resolves against. An installed copy gets `~/.scribejay` instead of
    site-packages: nothing reads a relative path from cwd any more, but a
    scheduled job whose working directory is inside the install is a job that
    can drop a stray file into it.
    """
    if (_INSTALL_ROOT / "pyproject.toml").exists():
        return _INSTALL_ROOT
    return config.config_dir()


def label_for(key: str) -> str:
    """`daily_commits` -> `local.scribejay.dailycommits`.

    The underscores come out because that is what the eight committed plists
    were called, and a label is what `launchctl` and any dashboard use to
    identify a job. Renaming them would orphan every currently-loaded agent.
    """
    return LABEL_PREFIX + key.replace("_", "")


def plist_path(key: str) -> Path:
    return LAUNCH_AGENTS / f"{label_for(key)}.plist"


def logs_dir() -> Path:
    """Absolute, via config.resolve_path — the same resolver core/logs.py uses.

    A relative value here would land in the plist as-is and launchd would
    resolve it against WorkingDirectory, so the launchd log and the task's own
    run log could end up in different places from the same setting."""
    return config.resolve_path(config.getenv("SCRIBEJAY_LOGS_DIR"))


def plist_for(task: registry.Task) -> dict:
    """The launchd job description for one task.

    `<logs>/<key>.launchd.log` catches what launchd itself says — a failed exec,
    an unhandled traceback — which is separate from `<logs>/<key>.log`, the
    run log the task writes through `setup_logger`. Both basenames are the task
    key, and docs/architecture.md is explicit that run history is keyed off
    them, so neither may change.
    """
    launchd_log = str(logs_dir() / f"{task.key}.launchd.log")
    return {
        "Label": label_for(task.key),
        "ProgramArguments": [sys.executable, "-m", f"scribejay.{task.key}"],
        "WorkingDirectory": str(working_directory()),
        "StartCalendarInterval": {"Hour": task.hour, "Minute": task.minute},
        "StandardOutPath": launchd_log,
        "StandardErrorPath": launchd_log,
        # Never at load: `scribejay schedule install` would otherwise fire
        # eight model jobs at once, on a machine the user is sitting at.
        "RunAtLoad": False,
    }


def _domain() -> str:
    return f"gui/{os.getuid()}"


def _launchctl(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["/bin/launchctl", *args],
                          capture_output=True, text=True, timeout=30)


def _bootout(label: str) -> None:
    """Unload an agent, ignoring "it was not loaded".

    bootout, not unload: it is the modern verb and the one that pairs with
    bootstrap, which is what `launchd/install.sh` has always used.
    """
    _launchctl("bootout", f"{_domain()}/{label}")


def _bootstrap(path: Path) -> tuple[bool, str]:
    result = _launchctl("bootstrap", _domain(), str(path))
    return result.returncode == 0, (result.stderr or result.stdout).strip()


def is_loaded(label: str) -> bool:
    return _launchctl("print", f"{_domain()}/{label}").returncode == 0


def install() -> int:
    """Write and load a plist for every enabled task; remove the rest.

    Removing the disabled ones is half the command, not a tidy-up. A user who
    turns Strava off in the settings screen and re-runs this expects the 5:50
    job to stop existing — leaving a stale agent loaded would mean it kept
    waking up to log a skip, which is the noise Phase 3 removed.
    """
    LAUNCH_AGENTS.mkdir(parents=True, exist_ok=True)
    logs_dir().mkdir(parents=True, exist_ok=True)
    working_directory().mkdir(parents=True, exist_ok=True)

    enabled = {t.key for t in registry.enabled_tasks()}
    failed = 0

    for task in registry.TASKS:
        path = plist_path(task.key)
        if task.key not in enabled:
            if path.exists():
                _bootout(label_for(task.key))
                path.unlink()
                print(f"removed  {label_for(task.key):40} "
                      f"{registry.is_ready(task.key)[1]}")
            continue

        path.write_bytes(plistlib.dumps(plist_for(task)))
        _bootout(label_for(task.key))
        ok, detail = _bootstrap(path)
        if ok:
            print(f"installed {label_for(task.key):39} "
                  f"{task.hour:02d}:{task.minute:02d}  {task.label}")
        else:
            failed += 1
            print(f"FAILED    {label_for(task.key):39} {detail}", file=sys.stderr)

    print(f"\ninterpreter: {sys.executable}")
    print(f"logs:        {logs_dir()}")
    if not enabled:
        print("\nNothing is enabled, so nothing was scheduled. "
              "Run `scribejay status` to see why.")
    return 1 if failed else 0


def remove() -> int:
    """Unload and delete every generated agent. Leaves selfheal alone."""
    removed = 0
    for task in registry.TASKS:
        path = plist_path(task.key)
        if not path.exists():
            continue
        _bootout(label_for(task.key))
        path.unlink()
        removed += 1
        print(f"removed {label_for(task.key)}")
    if not removed:
        print("Nothing to remove.")
    if (LAUNCH_AGENTS / f"{SELFHEAL_LABEL}.plist").exists():
        print(f"\nLeft {SELFHEAL_LABEL} in place — it is installed by "
              "launchd/install.sh, not by this command.")
    return 0


def status() -> int:
    """What is actually installed, next to what should be.

    Reports the plist on disk and whether launchd has it loaded as two separate
    facts, because they come apart: a brew upgrade leaves the file untouched
    and the job unexecutable, which is the whole reason selfheal exists.
    """
    for task in registry.TASKS:
        label = label_for(task.key)
        path = plist_path(task.key)
        ready, why = registry.is_ready(task.key)

        if not path.exists():
            state = "not installed"
        elif is_loaded(label):
            state = "loaded"
        else:
            state = "ON DISK, NOT LOADED"

        want = "should run" if ready else "disabled"
        print(f"  {state:20} {want:10} {task.hour:02d}:{task.minute:02d}  "
              f"{label:40} {why}")

    selfheal = "loaded" if is_loaded(SELFHEAL_LABEL) else "not installed"
    print(f"\n  {selfheal:20} {'':10}        {SELFHEAL_LABEL} "
          "(installed by launchd/install.sh)")
    print(f"\nagents: {LAUNCH_AGENTS}")
    return 0
